---
- name: Install influxdb packages
  apt: update_cache=yes name="{{ item }}"
  with_items:
    - influxdb
    - influxdb-client
  notify:
    - reload-systemctl
    - restart-influxdb

- include: initdb.yml
