---
- name: Install influxdb packages
  apt: name="{{ item }}"
  with_items:
    - influxdb
    - influxdb-client
  notify:
    - reload-systemctl
    - restart-influxdb

- include: influxdb_config.yml
- include: initdb.yml
