- hosts: all
  become: yes

  tasks:
    - name: bbb system init
      include_role:
        name: bbb
        tasks_from: baseinit
        
    - name: install mosquitto
      include_role:
        name: mosquitto
        tasks_from: install

    - name: install influxdb
      include_role:
        name: influxdb
        tasks_from: install

  roles:
    - { role: homeassistant }        