---

- hosts: bbb
  become: yes
  roles:
    - bbb
    - avahi
#    - mosquitto
    - influxdb
    - homeassistant
    - vx
  vars:
     prj: &prj smarthome
     vx_user: *prj
     homeassistant_user: *prj
