---
# defaults file for ansible-homeassistant

homeassistant_user: homeassistant
homeassistant_config: /home/{{ homeassistant_user }}/hass-config
homeassistant_version: latest
homeassistant_virtualenv: /home/{{ homeassistant_user }}/venv

homeassistant_git_config: https://github.com/vladspbru/hass-config.git

#homeassistant_additional_apt_dependencies: []
homeassistant_additional_apt_dependencies: 
  - gcc
  - build-essential
  - libxslt-dev
  - libxml2-dev
  - nmap
  - net-tools
  - libffi-dev
  - libssl-dev
  - python3-yaml
  - python3-lxml
  - python3-netifaces
    
#homeassistant_additional_pip_dependencies: []
homeassistant_additional_pip_dependencies: 
  - appdirs
  - packaging
  - colorlog
  - wheel
