# handlers file for ansible-homeassistant
---
- name: reload-systemctl
  command: systemctl daemon-reload
  become: yes

- name: restart-homeassistant
  service: name=homeassistant state=restarted
  become: yes

- name: reload-avahi
  become: yes
  service: 
    name: avahi
    state: restarted
