---
- name: reload-systemctl
  command: systemctl daemon-reload
  become: yes

- name: restart-microsd-automount
  become: yes
  service: 
    name: media-microsd.automount
    daemon_reload: yes
    enabled: yes
    state: restarted
 
