# handlers file for ansible-homeassistant
---
- name: reload-systemctl
  command: systemctl daemon-reload
  become: yes

- name: restart-mqtt2influxdb
  service: name=mqtt2influxdb state=restarted
  become: yes
