    - name: Remove some packages
      apt: name={{ item }} state=absent purge=yes
      with_items:
        - ardupilot-*
        - c9-core-installer
        - nodejs
        - bonescript
        - bone101
        - apache2*

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes        
        
    - name: Install mc git and some packages
      apt: update_cache=yes name={{ item }}
      with_items:
        - mc
        - tmux
        - git
        
        
