---
- name: Remove some packages
  apt: name="{{ item }}" state=absent purge=yes
  with_items:
    - ardupilot-*
    - c9-core-installer
    - nodejs
    - bonescript
    - bone101
    - apache2*
    - librobotcontrol

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes        
    
- name: Install mc git and some packages
  apt: name="{{ item }}"
  with_items:
    - mc
    - tmux
    - git

- name: Set datetime zone
  command: "timedatectl set-timezone Europe/Moscow"


- name: "Install microsd mount file"
  template: 
    src: microsd.mount.j2
    dest: /etc/systemd/system/media-microsd.mount
    mode: 0755
    owner: root
    group: root
  become: yes
  notify:
    - reload-systemctl

- name: "Install microsd automount file"
  template: 
    src: microsd.automount.j2
    dest: /etc/systemd/system/media-microsd.automount
    mode: 0755
    owner: root
    group: root
  become: yes
  notify:
    - reload-systemctl
    - restart-microsd-automount
  
