- name: Update dist packages to the latest version
    apt:
    update_cache: yes
    upgrade: dist

- name: Clean dependencies that are no longer required
    apt:
    autoremove: yes        
        
        
