---
- name: install commonly-named packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - python3
  - python3-pip
  - python3-dev
  - python3-yaml
  - python3-lxml
  - python3-netifaces
  - libxslt-dev
  - libxml2-dev
  - gcc
  - build-essential
  - nmap
  - net-tools
  - libffi-dev
  - libssl-dev
 
- name: create user
  user:
    name: "{{ ha_user }}"
    comment: "Home Assistant"
    createhome: no
    system: yes
    shell: "/sbin/nologin"

- name: create directory
  file:
    path: "{{ ha_conf_dir }}"
    state: directory
    mode: 02775
    owner: "{{ ha_user }}"
    group: "{{ ha_user }}"

- name: install required python modules
  pip:
    name: "{{ item }}"
    extra_args: "--upgrade"
    executable: pip3
  with_items:
    - appdirs
    - packaging
    - colorlog
    - wheel
    
- name: install defined version of Home Assistant
  pip:
    name: homeassistant
    version: "{{ ha_version }}"
    executable: pip3
  when: ha_version is defined

- name: install latest version of Home Assistant
  pip:
    name: homeassistant
    extra_args: "--upgrade"
    executable: pip3
  when: ha_version is undefined
