# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2018 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- include: ../vars.yml
- include: installation.yml
- include: systemd.yml
- include: firewall.yml
  when: ansible_distribution == "Fedora"
