    - name: Install mosquitto packages
      apt: update_cache=yes name={{ item }}
      with_items:
        - mosquitto
        - mosquitto-clients 
        
    - name: install systemd unit file
      template:
        src: mosquitto.service.j2
        dest: "/etc/systemd/system/mosquitto.service"
        owner: root
        group: root
        mode: 0644

    - name: start mosquitto
      systemd:
        name: mosquitto
        daemon_reload: yes
        enabled: yes
        state: started	
