- name: Install mosquitto packages
  apt: update_cache=yes name="{{ item }}"
  with_items:
    - mosquitto
    - mosquitto-clients 
    
- name: install systemd unit file
  template:
    src: mosquitto.service.j2
    dest: "/etc/systemd/system/mosquitto.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload-systemctl
    - restart-mosquitto

