- name: Install mosquitto packages
  apt: name="{{ item }}"
  with_items:
    - mosquitto
    - mosquitto-clients 
    
- name: install systemd unit file
  template:
    src: mosquitto.service.j2
    dest: "/etc/systemd/system/mosquitto.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload-systemctl
    - restart-mosquitto

- name: publish mqtt service on avahi 
  copy:
    src: mosquitto.service
    dest: "/etc/avahi/services/mosquitto.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart-avahi

